development:
  cloud_name: hdeop8wed
  api_key: '975881341593778'
  api_secret: rzNUOwxYM4yPFsJb2tjqbvyWho4
  enhance_image_tag: true
  static_image_support: false
  secure: true
production:
  cloud_name: hdeop8wed
  api_key: '975881341593778'
  api_secret: rzNUOwxYM4yPFsJb2tjqbvyWho4
  enhance_image_tag: true
  static_image_support: true
  secure: true
test:
  cloud_name: hdeop8wed
  api_key: '975881341593778'
  api_secret: rzNUOwxYM4yPFsJb2tjqbvyWho4
  enhance_image_tag: true
  static_image_support: false
  secure: true